### ISSUE TITLE
Convert timestamps in manifest.json to ISO-8601

### ISSUE THREAD

**Issue by AdamWHY2K** [danieladov/JellyfinPluginManifest#1]
Currently, navigating to the merge versions plugin via the catalog throws this error:

```
Error: Couldn't parse ISO 8601 date string '2024-05-15 16:45:00'
    at o ([REDACTED]/web/main.jellyfin.bundle.js?f1238435f421c71ad785:2:301722)
    at [REDACTED]/web/plugins-plugin.3420d67af1391b068d1a.chunk.js:1:9626
    at Array.map (<anonymous>)
    at en ([REDACTED]/web/plugins-plugin.3420d67af1391b068d1a.chunk.js:1:9435)
    at hu ([REDACTED]/web/node_modules.react-dom.bundle.js?f1238435f421c71ad785:2:60311)
    at xi ([REDACTED]/web/node_modules.react-dom.bundle.js?f1238435f421c71ad785:2:119252)
    at bs ([REDACTED]/web/node_modules.react-dom.bundle.js?f1238435f421c71ad785:2:108504)
    at vs ([REDACTED]/web/node_modules.react-dom.bundle.js?f1238435f421c71ad785:2:108432)
    at gs ([REDACTED]/web/node_modules.react-dom.bundle.js?f1238435f421c71ad785:2:108295)
    at as ([REDACTED]/web/node_modules.react-dom.bundle.js?f1238435f421c71ad785:2:105130)
```

I'm guessing `2024-05-15 16:45:00` needs to be `2024-05-15T16:45:00` and all the other timestamps need to follow suit

**Comment by danieladov** [comment]
Fixed, thanks!
